### ISSUE TITLE
Feature: Custom styling / custom interface

### ISSUE THREAD

**Issue by viezel** [ePay/ios-sdk-lib#1]
Hey,

Fedt at I har udviklet en wrapper til iOS og Android. Jeg vil dog ønske at jeg kunne en af følgende 2 muligheder:
1. Custom style det webView (PaymentWindow). Så det er muligt at tilpasse et specifikt kunde.
2. Give mulighed for at interagere med API frem for at bruge jeres PaymentWindow. På den måde jeg kunne tilgå jeres ePayLib library uden at skulle bruge jeres window, og derfor 100% selv styre styling mv.

Håber det bliver muligt. Og fedt at I er begyndt at rykke på native!! 

Mads

**Comment by epay-thomas** [comment]
Hej Mads,

Tak for din interesse omkring vores IOS library.

Du har mulighed for at custom style vores mobile vindue via CSS URL’en. Her kan du overstyre alle elementer i vinduet via et stykke CSS, som du har placeret på egen server. Vi vil da hente denne CSS og bygge det ind i betalingsvinduet (embed). Du kan læse om cssurl parameteren her: http://tech.epay.dk/da/betalingsvindue-parametre.

Til dit spørgsmål omkring at interagere direkte med vores platform fra app’en, så er det ikke muligt. Ifølge reglerne skal kortdata indtastes via en browserløsning, der er hosted i vores PCI miljø.

Med venlig hilsen / Kind Regards
Thomas Knudsen

ePay A/S
Phn.:   (+45) 98 13 90 40
Dir.:     (+45) 96 31 71 47
Web:  www.epay.euhttp://www.epay.eu/
Mail:   thomas@epay.eumailto:thomas@epay.eu

Fra: Mads Møller [mailto:notifications@github.com]
Sendt: 29. januar 2014 18:57
Til: ePay/ios-sdk-lib
Emne: [ios-sdk-lib] Feature: Custom styling / custom interface (#1)

Hey,

Fedt at I har udviklet en wrapper til iOS og Android. Jeg er dog ønske at jeg kunne en af følgende 2 muligheder:
1. ```
    Custom style det webView (PaymentWindow). Så det er muligt at tilpasse et specifikt kunde.
   ```
2. ```
    Give mulighed for at interagere med API frem for at bruge jeres PaymentWindow. På den måde jeg kunne tilgå jeres ePayLib library uden at skulle bruge jeres window, og derfor 100% selv styre styling mv.
   ```

Håber det bliver muligt. Og fedt at I er begyndt at rykke på native!!

Mads

**Comment by storkie** [comment]
Til mobilvinduet benyttes parameteren mobilecssurl:
http://tech.epay.dk/da/specifikation#456

**Comment by viezel** [comment]
Tak for hurtig svar. Skal det forståes at jeg skal override styles, eller bliver de erstattet?
Det ville jo være langt mere simpelt hvis de blev erstattet, ellers skal jeg jo igang med at override lange styles.

Derudover, er der et direkte link som jeg vil kunne bruge i en browser? Det vil jo være langt nemmere at kunne inspicere DOM elementerne fra en computer, end at skulle style direkte i simulatoren.

**Comment by storkie** [comment]
Den angivne mobilecssurl bliver indsat efter ePay's stylesheet, så du kan override hele eller dele af stylesheetet. Grunden til, at vi har gjort det sådan, er, at mange kunder kun vil override dele af vores stylesheet. ThemeRoller kan give et godt udgangspunkt, hvis man vil lave en fuldstændig ændring af det eksisterende layout.

Der er et direkte link, du kan bruge, her:
http://tech.epay.dk/da/betalingsvindue-integration#334
Husk at sætte parameteren mobile=2

**Comment by viezel** [comment]
mange tak for svar.
